"use client";

import { FormEvent, useState } from "react";
import { Clock3, LogOut, MapPin, PackageCheck, UserRound } from "lucide-react";
import { AddressForm } from "@/components/address-form";
import { useGoldenStore } from "@/lib/store";
import { formatCurrency, shortDate } from "@/lib/utils";

const STEPS = ["PENDING", "CONFIRMED", "PACKED", "SHIPPED", "COMPLETED"] as const;
const stepLabel: Record<(typeof STEPS)[number], string> = { PENDING: "Pesanan dibuat", CONFIRMED: "Dikonfirmasi", PACKED: "Dikemas", SHIPPED: "Dikirim", COMPLETED: "Selesai" };

export default function AccountPage() {
  const { customerSession, customerAddresses, orders, registerCustomer, logoutCustomer, saveCustomerAddress, deleteCustomerAddress } = useGoldenStore();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState("");
  const register = (event: FormEvent) => { event.preventDefault(); if (name && email && phone) registerCustomer({ name, email, phone }); };
  if (!customerSession) return <section className="panel auth-shell" style={{ maxWidth: 620, margin: "0 auto" }}><div className="eyebrow"><UserRound size={14} /> Akun pembeli</div><h1>Buat akun untuk belanja lebih mudah</h1><p className="muted">Buat akun terlebih dahulu untuk mengatur alamat penerima, toko, dan pengembalian. Setelah akun dibuat, pilihan provinsi, kabupaten/kota, kecamatan, GPS, dan peta Google Maps tersedia di halaman ini.</p><form className="stack" onSubmit={register}><div className="field"><label>Nama lengkap</label><input className="input" value={name} onChange={(e) => setName(e.target.value)} required /></div><div className="field-grid"><div className="field"><label>Email</label><input className="input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="field"><label>No. WhatsApp</label><input className="input" value={phone} onChange={(e) => setPhone(e.target.value)} required /></div></div><button className="button" type="submit"><UserRound size={16} /> Buat akun & atur alamat</button></form></section>;
  const myOrders = orders.filter((order) => order.customerId === customerSession.id);
  return <div className="stack" style={{ gap: 22 }}><section className="panel"><div className="row-actions" style={{ justifyContent: "space-between" }}><div><div className="eyebrow"><UserRound size={14} /> Akun Saya</div><h1 style={{ marginBottom: 2 }}>{customerSession.name}</h1><p className="muted" style={{ margin: 0 }}>{customerSession.email} · {customerSession.phone}</p></div><button className="button-outline" onClick={logoutCustomer}><LogOut size={16} /> Keluar</button></div></section><section className="grid grid-2"><div className="panel"><div className="eyebrow"><MapPin size={14} /> Pusat alamat</div><h2>Pengiriman, toko & retur</h2><AddressForm addresses={customerAddresses} recipientName={customerSession.name} phone={customerSession.phone} onSave={saveCustomerAddress} onDelete={deleteCustomerAddress} /></div><div className="panel"><div className="eyebrow"><PackageCheck size={14} /> Pesanan saya</div><h2>Riwayat & status</h2>{myOrders.length === 0 ? <p className="muted">Belum ada pesanan dari akun ini.</p> : myOrders.map((order) => <article className="muted-box" key={order.id} style={{ marginBottom: 10 }}><div className="row-actions" style={{ justifyContent: "space-between" }}><strong>{order.orderNumber}</strong><span className="badge">{stepLabel[order.status as keyof typeof stepLabel] ?? order.status}</span></div><div className="muted tiny">{shortDate(order.createdAt)} · {formatCurrency(order.totalAmount)}</div>{order.paymentDueAt && order.paymentStatus === "UNPAID" ? <div className="payment-deadline"><Clock3 size={14} /> Bayar sebelum {new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.paymentDueAt))}</div> : null}<div className="order-timeline">{STEPS.map((step) => <span key={step} className={STEPS.indexOf(step) <= STEPS.indexOf(order.status as (typeof STEPS)[number]) ? "active" : ""}>{stepLabel[step]}</span>)}</div></article>)}</div></section></div>;
}
