"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Crosshair, MapPin, Plus, ShieldCheck } from "lucide-react";
import { addressSuggestions, googleMapsEmbedUrl, googleMapsUrl } from "@/lib/address-service";
import type { CustomerAddress } from "@/lib/types";

type Region = { id: string; name: string };
type Props = { addresses: CustomerAddress[]; recipientName: string; phone: string; onSave: (address: Omit<CustomerAddress, "id">) => void; onDelete: (id: string) => void };
const loadRegions = async (level: "provinces" | "regencies" | "districts", parentId?: string) => { const response = await fetch(`/api/regions?level=${level}${parentId ? `&parentId=${parentId}` : ""}`); if (!response.ok) throw new Error("Wilayah tidak dapat dimuat"); return response.json() as Promise<Region[]>; };

export function AddressForm({ addresses, recipientName, phone, onSave, onDelete }: Props) {
  const [label, setLabel] = useState("Rumah"); const [query, setQuery] = useState(""); const [detail, setDetail] = useState(""); const [provinces, setProvinces] = useState<Region[]>([]); const [cities, setCities] = useState<Region[]>([]); const [districts, setDistricts] = useState<Region[]>([]); const [provinceId, setProvinceId] = useState(""); const [cityId, setCityId] = useState(""); const [districtId, setDistrictId] = useState(""); const [postalCode, setPostalCode] = useState(""); const [position, setPosition] = useState<{ latitude: number; longitude: number } | null>(null); const [message, setMessage] = useState("Pilih wilayah dan titik lokasi.");
  const province = provinces.find((item) => item.id === provinceId)?.name ?? ""; const city = cities.find((item) => item.id === cityId)?.name ?? ""; const district = districts.find((item) => item.id === districtId)?.name ?? ""; const suggestions = useMemo(() => query.length < 2 ? [] : addressSuggestions.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())).slice(0, 5), [query]); const verified = Boolean(provinceId && cityId && districtId && position);
  useEffect(() => { void loadRegions("provinces").then(setProvinces).catch(() => setMessage("Data wilayah belum dapat dimuat.")); }, []);
  useEffect(() => { if (provinceId) void loadRegions("regencies", provinceId).then(setCities); }, [provinceId]);
  useEffect(() => { if (cityId) void loadRegions("districts", cityId).then(setDistricts); }, [cityId]);
  const chooseSuggestion = (item: typeof addressSuggestions[number]) => { setQuery(item.label); setPostalCode(item.postalCode); setPosition({ latitude: item.latitude, longitude: item.longitude }); setMessage("Titik lokasi tersimpan. Pilih wilayah pada dropdown."); };
  const useGps = () => { if (!navigator.geolocation) return setMessage("GPS tidak tersedia."); navigator.geolocation.getCurrentPosition((value) => { setPosition({ latitude: value.coords.latitude, longitude: value.coords.longitude }); setMessage("Titik GPS tersimpan."); }, () => setMessage("Izin GPS ditolak."), { enableHighAccuracy: true, timeout: 10000 }); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!detail || !verified) return setMessage("Lengkapi wilayah, alamat, dan titik lokasi."); onSave({ type: "RECIPIENT", label, recipientName, phone, province, city, district, detail, postalCode, isPrimary: !addresses.length, latitude: position?.latitude, longitude: position?.longitude, mapsUrl: position ? googleMapsUrl(position.latitude, position.longitude) : undefined, isVerified: true }); setLabel("Rumah"); setQuery(""); setDetail(""); setPostalCode(""); setPosition(null); setMessage("Alamat tersimpan."); };
  return <div className="address-system">{addresses.filter((address) => (address.type ?? "RECIPIENT") === "RECIPIENT").map((address) => <div className="address-card" key={address.id}><div><strong>{address.label} {address.isPrimary ? "· Utama" : ""}</strong><div>{address.recipientName} · {address.phone}</div><div className="muted tiny">{address.detail}, {address.district}, {address.city}, {address.province} {address.postalCode}</div></div><button className="button-ghost" type="button" onClick={() => onDelete(address.id)}>Hapus</button></div>)}<form className="stack" onSubmit={submit} style={{ marginTop: 14 }}><div className="field-grid"><div className="field"><label>Label alamat</label><input className="input" value={label} onChange={(e) => setLabel(e.target.value)} /></div><div className="field"><label>Autocomplete alamat</label><input className="input" value={query} onChange={(e) => setQuery(e.target.value)} />{suggestions.length ? <div className="address-suggestions">{suggestions.map((item) => <button type="button" key={item.label} onClick={() => chooseSuggestion(item)}><MapPin size={14} />{item.label}</button>)}</div> : null}</div></div><div className="field-grid"><div className="field"><label>Provinsi</label><select className="select" value={provinceId} onChange={(e) => { setProvinceId(e.target.value); setCityId(""); setDistrictId(""); }} required><option value="">Pilih provinsi</option>{provinces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Kabupaten/Kota</label><select className="select" value={cityId} onChange={(e) => { setCityId(e.target.value); setDistrictId(""); }} disabled={!provinceId} required><option value="">Pilih kabupaten/kota</option>{cities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Kecamatan</label><select className="select" value={districtId} onChange={(e) => setDistrictId(e.target.value)} disabled={!cityId} required><option value="">Pilih kecamatan</option>{districts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Kode pos</label><input className="input" value={postalCode} onChange={(e) => setPostalCode(e.target.value)} /></div></div><div className="field"><label>Alamat lengkap</label><textarea className="textarea" value={detail} onChange={(e) => setDetail(e.target.value)} required /></div><div className="location-row"><button className="button-outline" type="button" onClick={useGps}><Crosshair size={16} /> Gunakan GPS</button><span className={verified ? "location-status ready" : "location-status"}><ShieldCheck size={15} /> {message}</span></div>{position ? <iframe className="address-map" title="Validasi lokasi" src={googleMapsEmbedUrl(position.latitude, position.longitude)} loading="lazy" /> : null}<button className="button-outline" type="submit"><Plus size={16} /> Simpan alamat</button></form></div>;
}
