import { AppState } from "@/lib/types";

export const appName = "Golden Store";

export const seedState: AppState = {
  theme: "dark",
  adminSession: null,
  categories: [
    {
      id: "cat-electronics",
      name: "Elektronik",
      slug: "elektronik",
      description: "Gadget premium dan perangkat harian.",
      isActive: true,
    },
    {
      id: "cat-fashion",
      name: "Fashion",
      slug: "fashion",
      description: "Pakaian dan aksesoris bernuansa premium.",
      isActive: true,
    },
    {
      id: "cat-home",
      name: "Home Living",
      slug: "home-living",
      description: "Kebutuhan rumah yang fungsional dan elegan.",
      isActive: true,
    },
    {
      id: "cat-beauty",
      name: "Beauty",
      slug: "beauty",
      description: "Perawatan diri untuk tampilan terbaik.",
      isActive: true,
    },
  ],
  paymentMethods: [
    {
      id: "pay-cod",
      type: "COD",
      label: "Bayar di Tempat",
      details: "Cocok untuk pembeli yang ingin bayar saat barang diterima.",
      accountName: "-",
      accountNumber: "-",
      isActive: true,
    },
    {
      id: "pay-dana",
      type: "DANA",
      label: "DANA",
      details: "Transfer ke akun e-wallet resmi Golden Store.",
      accountName: "Golden Store",
      accountNumber: "0812 3456 7890",
      isActive: true,
    },
    {
      id: "pay-bank",
      type: "BANK",
      label: "Bank Transfer",
      details: "Transfer ke rekening bank yang disediakan admin.",
      accountName: "PT Golden Store Indonesia",
      accountNumber: "1234567890",
      isActive: true,
    },
  ],
  banners: [
    { id: "banner-1", title: "Promo pilihan minggu ini", subtitle: "Temukan koleksi favorit dengan penawaran spesial.", imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=85", link: "/products", isActive: true },
    { id: "banner-2", title: "Gaya baru, harga terbaik", subtitle: "Produk berkualitas untuk kebutuhanmu setiap hari.", imageUrl: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1600&q=85", link: "/products", isActive: true },
  ],
  products: [
    {
      id: "prd-aurora-headphones",
      name: "Aurora Headphones",
      slug: "aurora-headphones",
      description: "Headphone nirkabel dengan bass tebal, mode ANC, dan desain emas elegan.",
      categoryId: "cat-electronics",
      price: 1299000,
      compareAtPrice: 1599000,
      stock: 18,
      sku: "GS-EL-001",
      isFeatured: true,
      isActive: true,
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1518441902117-f0a4f9f1f9b7?auto=format&fit=crop&w=1200&q=80",
      ],
      tags: ["audio", "ANC", "premium"],
      rating: 4.9,
      reviewsCount: 128,
    },
    {
      id: "prd-golden-watch",
      name: "Golden Watch",
      slug: "golden-watch",
      description: "Jam tangan modern dengan strap nyaman dan tampilan mewah.",
      categoryId: "cat-fashion",
      price: 899000,
      compareAtPrice: 1199000,
      stock: 12,
      sku: "GS-FS-010",
      isFeatured: true,
      isActive: true,
      images: [
        "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?auto=format&fit=crop&w=1200&q=80",
      ],
      tags: ["watch", "style", "new"],
      rating: 4.8,
      reviewsCount: 91,
    },
    {
      id: "prd-luxe-lamp",
      name: "Luxe Ambient Lamp",
      slug: "luxe-ambient-lamp",
      description: "Lampu meja hangat untuk suasana rumah yang lebih hidup dan nyaman.",
      categoryId: "cat-home",
      price: 459000,
      stock: 0,
      sku: "GS-HM-004",
      isFeatured: true,
      isActive: true,
      images: [
        "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
      ],
      tags: ["lamp", "home", "warm"],
      rating: 4.7,
      reviewsCount: 54,
    },
    {
      id: "prd-glow-serum",
      name: "Glow Serum",
      slug: "glow-serum",
      description: "Serum harian dengan formula ringan dan tampilan kemasan premium.",
      categoryId: "cat-beauty",
      price: 239000,
      stock: 34,
      sku: "GS-BE-002",
      isFeatured: true,
      isActive: true,
      images: [
        "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
      ],
      tags: ["skincare", "glow", "hydrating"],
      rating: 4.6,
      reviewsCount: 73,
    },
    {
      id: "prd-luxe-bag",
      name: "Luxe Tote Bag",
      slug: "luxe-tote-bag",
      description: "Tas serbaguna untuk kerja, kuliah, dan aktivitas harian.",
      categoryId: "cat-fashion",
      price: 679000,
      stock: 21,
      sku: "GS-FS-022",
      isFeatured: true,
      isActive: true,
      images: [
        "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
      ],
      tags: ["bag", "daily", "minimal"],
      rating: 4.8,
      reviewsCount: 66,
    },
    {
      id: "prd-smart-speaker",
      name: "Smart Speaker Mini",
      slug: "smart-speaker-mini",
      description: "Speaker ringkas dengan suara jernih dan konektivitas cepat.",
      categoryId: "cat-electronics",
      price: 349000,
      stock: 8,
      sku: "GS-EL-021",
      isFeatured: true,
      isActive: true,
      images: [
        "https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&w=1200&q=80",
      ],
      tags: ["speaker", "smart", "music"],
      rating: 4.5,
      reviewsCount: 39,
    },
  ],
  cart: [
    {
      productId: "prd-golden-watch",
      name: "Golden Watch",
      slug: "golden-watch",
      price: 899000,
      quantity: 1,
      image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1200&q=80",
      stock: 12,
    },
  ],
  orders: [
    {
      id: "ord-001",
      orderNumber: "GS-00001",
      customerName: "Siti Aisyah",
      customerPhone: "081234567890",
      customerAddress: "Jl. Melati 12, Bandung",
      mapsLink: "https://maps.google.com",
      notes: "Mohon antar siang hari.",
      status: "SHIPPED",
      paymentStatus: "VERIFIED",
      paymentMethodId: "pay-dana",
      paymentProofUrl: "",
      totalAmount: 1788000,
      shippingFee: 25000,
      adminNote: "Packing aman, kirim sore.",
      items: [
        {
          productId: "prd-aurora-headphones",
          productName: "Aurora Headphones",
          unitPrice: 1299000,
          quantity: 1,
          subtotal: 1299000,
          image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
        },
        {
          productId: "prd-glow-serum",
          productName: "Glow Serum",
          unitPrice: 239000,
          quantity: 2,
          subtotal: 478000,
          image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
        },
      ],
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
    {
      id: "ord-002",
      orderNumber: "GS-00002",
      customerName: "Budi Santoso",
      customerPhone: "081998877665",
      customerAddress: "Jl. Kenanga 8, Jakarta",
      mapsLink: "https://maps.google.com",
      notes: "Hubungi sebelum kirim.",
      status: "CONFIRMED",
      paymentStatus: "PAID",
      paymentMethodId: "pay-bank",
      paymentProofUrl: "",
      totalAmount: 1048000,
      shippingFee: 20000,
      adminNote: "",
      items: [
        {
          productId: "prd-luxe-bag",
          productName: "Luxe Tote Bag",
          unitPrice: 679000,
          quantity: 1,
          subtotal: 679000,
          image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
        },
        {
          productId: "prd-smart-speaker",
          productName: "Smart Speaker Mini",
          unitPrice: 349000,
          quantity: 1,
          subtotal: 349000,
          image: "https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&w=1200&q=80",
        },
      ],
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    },
  ],
};
